version: '2.0'

services:
  memcache:
    image: memcached
    container_name: pitrix-memcache
    ports:
      - "${MEMCACHED_PORT}:11211"
  # Pitrix webconsole
  console:
    build:
      context: ./common
      args:
        project_name: pitrix-webconsole
        gunicorn_conf: console_gunicorn_conf.py
        project_settings: web_console_settings.py
    image: pitrix-web/console
    container_name: console
    ports:
      - "${CONSOLE_PORT}:80"
    extra_hosts:
      - "api.ciscomfg.net:139.198.127.3"
    volumes:
      - "${CONSOLE_SRC}:/pitrix/lib/pitrix-webconsole"
      - "${CONSOLE_LOG_DIR}:/pitrix/log"
      - "${CONSOLE_LOG_DIR}:/var/log/gunicorn"
    depends_on:
      - memcache
  # Pitrix webappcenter
  appcenter:
    build:
      context: ./common
      args:
        project_name: pitrix-webappcenter
        gunicorn_conf: appcenter_gunicorn_conf.py
        project_settings: web_appcenter_settings.py
    image: pitrix-web/appcenter
    container_name: appcenter
    ports:
      - "${APPCENTER_PORT}:80"
    extra_hosts:
      - "api.ciscomfg.net:139.198.127.3"
    volumes:
      - "${APPCENTER_SRC}:/pitrix/lib/pitrix-webappcenter"
      - "${APPCENTER_LOG_DIR}:/pitrix/log"
      - "${APPCENTER_LOG_DIR}:/var/log/gunicorn"
    depends_on:
      - memcache
  # Pitrix websupervisor
  supervisor:
    build:
      context: ./common
      args:
        project_name: pitrix-websupervisor
        gunicorn_conf: supervisor_gunicorn_conf.py
        project_settings: web_supervisor_settings.py
    image: pitrix-web/supervisor
    container_name: supervisor
    ports:
      - "${SUPERVISOR_PORT}:80"
    extra_hosts:
      - "api.ciscomfg.net:139.198.127.3"
    volumes:
      - "${SUPERVISOR_SRC}:/pitrix/lib/pitrix-websupervisor"
      - "${SUPERVISOR_LOG_DIR}:/pitrix/log"
      - "${SUPERVISOR_LOG_DIR}:/var/log/gunicorn"
    depends_on:
      - memcache
  # Nginx for QingStor Portal
  nginx:
    build: ./nginx
    image: pitrix-web/nginx
    container_name: pitrix-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "${CONSOLE_SRC}/static:/pitrix/lib/pitrix-webconsole/static"
      - "${APPCENTER_SRC}/static:/pitrix/lib/pitrix-webappcenter/static"
      - "${SUPERVISOR_SRC}/static:/pitrix/lib/pitrix-websupervisor/static"
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - console:console
      - appcenter:appcenter
    #environment:
      #- NGINX_SERVER_NAMES_HASH_MAX_SIZE=512
      #- NGINX_SERVER_NAMES_HASH_BUCKET_SIZE=64
    depends_on:
      - console
      - appcenter
      - supervisor
