FROM nginx

#ADD ./nginx.conf /etc/nignx/nginx.conf
ADD ./conf.d /etc/nginx/conf.d

# static files mount path
VOLUME "/pitrix/lib/pitrix-webconsole/static"
VOLUME "/pitrix/lib/pitrix-webappcenter/static"
#VOLUME "/pitrix/lib/pitrix-websupervisor/static"
